name: Create Release

on:
  push:
    tags:
      - '*'
    branches:
      - "!*"

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Tags
        run: git fetch --prune --unshallow --tags

      - name: Set Variables
        run: |
          echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
          git log --format=%B -n 1 $(git log -1 --pretty=format:"%h") | cat - > changes.txt
          if [[ "$(git describe --tags)" =~ .*"dev"|"qa"|"unstable".* ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_ENV;
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_ENV;
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build with Maven (no dependencies)
        run: mvn -q clean package -DskipTests

      - name: Create Mod Zip
        run: |
          cd ./.github/workflows/
          chmod +x ./zip.sh
          sh ./zip.sh "./../../" "DizturbsTweaksAndContentPack" 

      - name: Publish Release on GitHub
        uses: "ncipollo/release-action@v1.12.0"
        with:
          allowUpdates: true
          name: ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          draft: false
          prerelease: '${{ env.IS_PRERELEASE }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ".github/workflows/artifacts/*"