name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build with Maven (no dependencies)
        run: mvn -q clean package -DskipTests

      - name: Prepare release ZIP
        run: |
          mkdir -p release/jars
          cp target/*.jar release/jars/
          cp -r data release/
          cp mod_info.json release/
          cd release
          zip -r "../${{ github.event.repository.name }}.zip" *

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}